config/routes.rb
Algamswebsvc::Application.routes.draw do
  resources :cell_towers

  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"

  resources :usersubnums

  resources :users, except: :new

  resources :locweb_thepics

  resources :custpayments

  resources :btc_gsm_sig_survs

  resources :custinvoices

  get '/signup' => 'users#new'
  get '/towers_gmap' => 'cell_towers#towers_gmap'
  get '/algam' => 'sessions#new'
  post '/signin' => 'sessions#new'
  get '/signout' => 'sessions#destroy', via: :delete
  resources :sessions, only: :create

  root :controller => 'main', :action => :index

  get '/admin' => 'sessions#new'

  get "*rest" => "main#not_found"

end

app/models/locweb_thepic.rb
class LocwebThepic < ActiveRecord::Base
end

app/controllers/locweb_thepics_controller.rb
class LocwebThepicsController < ApplicationController
  before_action :set_locweb_thepic, only: [:show, :edit, :update, :destroy]

  # GET /locweb_thepics
  # GET /locweb_thepics.json
  def index
    @locweb_thepics = LocwebThepic.all
  end

  # GET /locweb_thepics/1
  # GET /locweb_thepics/1.json
  def show
  end

  # GET /locweb_thepics/new
  def new
    @locweb_thepic = LocwebThepic.new
  end

  # GET /locweb_thepics/1/edit
  def edit
  end

  # POST /locweb_thepics
  # POST /locweb_thepics.json
  def create
    @locweb_thepic = LocwebThepic.new(locweb_thepic_params)

    respond_to do |format|
      if @locweb_thepic.save
        format.html { redirect_to @locweb_thepic, notice: 'Locweb thepic was successfully created.' }
        format.json { render action: 'show', status: :created, location: @locweb_thepic }
      else
        format.html { render action: 'new' }
        format.json { render json: @locweb_thepic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locweb_thepics/1
  # PATCH/PUT /locweb_thepics/1.json
  def update
    respond_to do |format|
      if @locweb_thepic.update(locweb_thepic_params)
        format.html { redirect_to @locweb_thepic, notice: 'Locweb thepic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @locweb_thepic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locweb_thepics/1
  # DELETE /locweb_thepics/1.json
  def destroy
    @locweb_thepic.destroy
    respond_to do |format|
      format.html { redirect_to locweb_thepics_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_locweb_thepic
      @locweb_thepic = LocwebThepic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def locweb_thepic_params
      params.require(:locweb_thepic).permit(:posted_by, :pic_name, :pic_location_name, :pic_coords, :pic_timestamp, :pic_image_path, :pic_weather_currently, :pic_status, :pic_link)
    end
end

app/helpers/locweb_thepics_helper.rb
module LocwebThepicsHelper
end

app/views/locweb_thepics/_form.html.erb
<%= semantic_form_for @locweb_thepic do |f| %>
  <%= f.inputs do %>
    <%= f.input :posted_by %>
    <%= f.input :pic_name %>
    <%= f.input :pic_location_name %>
    <%= f.input :pic_coords %>
    <%= f.input :pic_timestamp %>
    <%= f.input :pic_image_path %>
    <%= f.input :pic_weather_currently %>
    <%= f.input :pic_status %>
    <%= f.input :pic_link %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input %>
  <% end %>
<% end %>

app/views/locweb_thepics/edit.html.erb
<h1>Editing locweb_thepic</h1>

<%= render 'form' %>

<%= link_to 'Show', @locweb_thepic %> |
<%= link_to 'Back', locweb_thepics_path %>

app/views/locweb_thepics/index.html.erb
<h1>Listing locweb_thepics</h1>

<table>
  <thead>
    <tr>
      <th>Posted by</th>
      <th>Pic name</th>
      <th>Pic location name</th>
      <th>Pic coords</th>
      <th>Pic timestamp</th>
      <th>Pic image path</th>
      <th>Pic weather currently</th>
      <th>Pic status</th>
      <th>Pic link</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @locweb_thepics.each do |locweb_thepic| %>
      <tr>
        <td><%= locweb_thepic.posted_by %></td>
        <td><%= locweb_thepic.pic_name %></td>
        <td><%= locweb_thepic.pic_location_name %></td>
        <td><%= locweb_thepic.pic_coords %></td>
        <td><%= locweb_thepic.pic_timestamp %></td>
        <td><%= locweb_thepic.pic_image_path %></td>
        <td><%= locweb_thepic.pic_weather_currently %></td>
        <td><%= locweb_thepic.pic_status %></td>
        <td><%= locweb_thepic.pic_link %></td>
        <td><%= link_to 'Show', locweb_thepic %></td>
        <td><%= link_to 'Edit', edit_locweb_thepic_path(locweb_thepic) %></td>
        <td><%= link_to 'Destroy', locweb_thepic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Locweb thepic', new_locweb_thepic_path %>

app/views/locweb_thepics/new.html.erb
<h1>New locweb_thepic</h1>

<%= render 'form' %>

<%= link_to 'Back', locweb_thepics_path %>

app/views/locweb_thepics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Posted by:</strong>
  <%= @locweb_thepic.posted_by %>
</p>

<p>
  <strong>Pic name:</strong>
  <%= @locweb_thepic.pic_name %>
</p>

<p>
  <strong>Pic location name:</strong>
  <%= @locweb_thepic.pic_location_name %>
</p>

<p>
  <strong>Pic coords:</strong>
  <%= @locweb_thepic.pic_coords %>
</p>

<p>
  <strong>Pic timestamp:</strong>
  <%= @locweb_thepic.pic_timestamp %>
</p>

<p>
  <strong>Pic image path:</strong>
  <%= @locweb_thepic.pic_image_path %>
</p>

<p>
  <strong>Pic weather currently:</strong>
  <%= @locweb_thepic.pic_weather_currently %>
</p>

<p>
  <strong>Pic status:</strong>
  <%= @locweb_thepic.pic_status %>
</p>

<p>
  <strong>Pic link:</strong>
  <%= @locweb_thepic.pic_link %>
</p>

<%= link_to 'Edit', edit_locweb_thepic_path(@locweb_thepic) %> |
<%= link_to 'Back', locweb_thepics_path %>