config/routes.rb
Algamswebsvc::Application.routes.draw do
  resources :cell_towers

  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"

  resources :usersubnums

  resources :users, except: :new

  resources :locweb_thepics

  resources :custpayments

  resources :btc_gsm_sig_survs

  resources :custinvoices

  get '/signup' => 'users#new'
  get '/towers_gmap' => 'cell_towers#towers_gmap'
  get '/algam' => 'sessions#new'
  post '/signin' => 'sessions#new'
  get '/signout' => 'sessions#destroy', via: :delete
  resources :sessions, only: :create

  root :controller => 'main', :action => :index

  get '/admin' => 'sessions#new'

  get "*rest" => "main#not_found"

end

app/models/cell_tower.rb
class CellTower < ActiveRecord::Base
  #Below property is in case we do not hve the
  #Lat and long which will take a geocode
  #and generate the lat/long
  #remember to add the css style sheet for the gmaps gem
  #acts_as_gmappable :process_geocoding => false

end

app/controllers/cell_towers_controller.rb
class CellTowersController < ApplicationController
  before_action :set_cell_tower, only: [:show, :edit, :update, :destroy]

  # GET /cell_towers
  # GET /cell_towers.json
  def index
    @cell_towers = CellTower.all
  end

  # GET /cell_towers/1
  # GET /cell_towers/1.json
  def show
  end

  # GET /cell_towers/new
  def new
    @cell_tower = CellTower.new
  end

  # GET /cell_towers/1/edit
  def edit
  end

  # POST /cell_towers
  # POST /cell_towers.json
  def create
    @cell_tower = CellTower.new(cell_tower_params)

    respond_to do |format|
      if @cell_tower.save
        format.html { redirect_to @cell_tower, notice: 'Cell tower was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cell_tower }
      else
        format.html { render action: 'new' }
        format.json { render json: @cell_tower.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cell_towers/1
  # PATCH/PUT /cell_towers/1.json
  def update
    respond_to do |format|
      if @cell_tower.update(cell_tower_params)
        format.html { redirect_to @cell_tower, notice: 'Cell tower was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cell_tower.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cell_towers/1
  # DELETE /cell_towers/1.json
  def destroy
    @cell_tower.destroy
    respond_to do |format|
      format.html { redirect_to cell_towers_url }
      format.json { head :no_content }
    end
  end

  def towers_gmap


  end





  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cell_tower
      @cell_tower = CellTower.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cell_tower_params
      params.require(:cell_tower).permit(:cgi, :cell_id, :site_name, :site, :latitude, :longitude, :btc_cell_id, :location_type, :node_b, :no_carriers, :eff_hsdpa_cap, :enhanced_uplink, :band)
    end
end

app/helpers/cell_towers_helper.rb
module CellTowersHelper
end

app/views/cell_towers/_form.html.erb
<%= simple_form_for(@cell_tower) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :cgi %>
    <%= f.input :cell_id %>
    <%= f.input :site_name %>
    <%= f.input :site %>
    <%= f.input :latitude %>
    <%= f.input :longitude %>
    <%= f.input :btc_cell_id %>
    <%= f.input :location_type %>
    <%= f.input :node_b %>
    <%= f.input :no_carriers %>
    <%= f.input :eff_hsdpa_cap %>
    <%= f.input :enhanced_uplink %>
    <%= f.input :band %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/cell_towers/_infowindow.html.erb
<div>
  <h3>Cell ID: <%= tower.cell_id %></h3>
  <h3>BTC Cell ID: <%= tower.btc_cell_id %></h3>
  <h3>Site Name: <%= tower.site %> - <%= tower.site_name %> </h3>
  <h3>Location Type: <%= tower.location_type %></h3>
</div>

app/views/cell_towers/edit.html.erb
<h1>Editing cell_tower</h1>

<%= render 'form' %>

<%= link_to 'Show', @cell_tower %> |
<%= link_to 'Back', cell_towers_path %>

app/views/cell_towers/index.html.erb
<h1>Listing cell_towers</h1>

<table>
  <thead>
    <tr>
      <th>Cgi</th>
      <th>Cell</th>
      <th>Site name</th>
      <th>Site</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Btc cell</th>
      <th>Location type</th>
      <th>Node b</th>
      <th>No carriers</th>
      <th>Eff hsdpa cap</th>
      <th>Enhanced uplink</th>
      <th>Band</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @cell_towers.each do |cell_tower| %>
      <tr>
        <td><%= cell_tower.cgi %></td>
        <td><%= cell_tower.cell_id %></td>
        <td><%= cell_tower.site_name %></td>
        <td><%= cell_tower.site %></td>
        <td><%= cell_tower.latitude %></td>
        <td><%= cell_tower.longitude %></td>
        <td><%= cell_tower.btc_cell_id %></td>
        <td><%= cell_tower.location_type %></td>
        <td><%= cell_tower.node_b %></td>
        <td><%= cell_tower.no_carriers %></td>
        <td><%= cell_tower.eff_hsdpa_cap %></td>
        <td><%= cell_tower.enhanced_uplink %></td>
        <td><%= cell_tower.band %></td>
        <td><%= link_to 'Show', cell_tower %></td>
        <td><%= link_to 'Edit', edit_cell_tower_path(cell_tower) %></td>
        <td><%= link_to 'Destroy', cell_tower, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cell tower', new_cell_tower_path %>

app/views/cell_towers/new.html.erb
<h1>New cell_tower</h1>

<%= render 'form' %>

<%= link_to 'Back', cell_towers_path %>

app/views/cell_towers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cgi:</strong>
  <%= @cell_tower.cgi %>
</p>

<p>
  <strong>Cell:</strong>
  <%= @cell_tower.cell_id %>
</p>

<p>
  <strong>Site name:</strong>
  <%= @cell_tower.site_name %>
</p>

<p>
  <strong>Site:</strong>
  <%= @cell_tower.site %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @cell_tower.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @cell_tower.longitude %>
</p>

<p>
  <strong>Btc cell:</strong>
  <%= @cell_tower.btc_cell_id %>
</p>

<p>
  <strong>Location type:</strong>
  <%= @cell_tower.location_type %>
</p>

<p>
  <strong>Node b:</strong>
  <%= @cell_tower.node_b %>
</p>

<p>
  <strong>No carriers:</strong>
  <%= @cell_tower.no_carriers %>
</p>

<p>
  <strong>Eff hsdpa cap:</strong>
  <%= @cell_tower.eff_hsdpa_cap %>
</p>

<p>
  <strong>Enhanced uplink:</strong>
  <%= @cell_tower.enhanced_uplink %>
</p>

<p>
  <strong>Band:</strong>
  <%= @cell_tower.band %>
</p>

<%= link_to 'Edit', edit_cell_tower_path(@cell_tower) %> |
<%= link_to 'Back', cell_towers_path %>