config/routes.rb
Algamswebsvc::Application.routes.draw do
  resources :cell_towers

  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"

  resources :usersubnums

  resources :users, except: :new

  resources :locweb_thepics

  resources :custpayments

  resources :btc_gsm_sig_survs

  resources :custinvoices

  get '/signup' => 'users#new'
  get '/towers_gmap' => 'cell_towers#towers_gmap'
  get '/algam' => 'sessions#new'
  post '/signin' => 'sessions#new'
  get '/signout' => 'sessions#destroy', via: :delete
  resources :sessions, only: :create

  root :controller => 'main', :action => :index

  get '/admin' => 'sessions#new'

  get "*rest" => "main#not_found"

end

app/models/usersubnum.rb
class Usersubnum < ActiveRecord::Base
end

app/controllers/usersubnums_controller.rb
class UsersubnumsController < ApplicationController
  before_action :set_usersubnum, only: [:show, :edit, :update, :destroy]

  # GET /usersubnums
  # GET /usersubnums.json
  def index
    @usersubnums = Usersubnum.all
  end

  # GET /usersubnums/1
  # GET /usersubnums/1.json
  def show
  end

  # GET /usersubnums/new
  def new
    @usersubnum = Usersubnum.new
  end

  # GET /usersubnums/1/edit
  def edit
  end

  # POST /usersubnums
  # POST /usersubnums.json
  def create
    @usersubnum = Usersubnum.new(usersubnum_params)

    respond_to do |format|
      if @usersubnum.save
        format.html { redirect_to @usersubnum, notice: 'Usersubnum was successfully created.' }
        format.json { render action: 'show', status: :created, location: @usersubnum }
      else
        format.html { render action: 'new' }
        format.json { render json: @usersubnum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usersubnums/1
  # PATCH/PUT /usersubnums/1.json
  def update
    respond_to do |format|
      if @usersubnum.update(usersubnum_params)
        format.html { redirect_to @usersubnum, notice: 'Usersubnum was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @usersubnum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usersubnums/1
  # DELETE /usersubnums/1.json
  def destroy
    @usersubnum.destroy
    respond_to do |format|
      format.html { redirect_to usersubnums_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usersubnum
      @usersubnum = Usersubnum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usersubnum_params
      params.require(:usersubnum).permit(:subnum, :status, :createdate)
    end
end

app/helpers/usersubnums_helper.rb
module UsersubnumsHelper
end

app/views/usersubnums/_form.html.erb
<%= form_for(@usersubnum) do |f| %>
  <% if @usersubnum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usersubnum.errors.count, "error") %> prohibited this usersubnum from being saved:</h2>

      <ul>
      <% @usersubnum.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subnum %><br>
    <%= f.number_field :subnum %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :createdate %><br>
    <%= f.datetime_select :createdate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/usersubnums/edit.html.erb
<h1>Editing usersubnum</h1>

<%= render 'form' %>

<%= link_to 'Show', @usersubnum %> |
<%= link_to 'Back', usersubnums_path %>

app/views/usersubnums/index.html.erb
<h1>Listing usersubnums</h1>

<table>
  <thead>
    <tr>
      <th>Subnum</th>
      <th>Status</th>
      <th>Createdate</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @usersubnums.each do |usersubnum| %>
      <tr>
        <td><%= usersubnum.subnum %></td>
        <td><%= usersubnum.status %></td>
        <td><%= usersubnum.createdate %></td>
        <td><%= link_to 'Show', usersubnum %></td>
        <td><%= link_to 'Edit', edit_usersubnum_path(usersubnum) %></td>
        <td><%= link_to 'Destroy', usersubnum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usersubnum', new_usersubnum_path %>

app/views/usersubnums/new.html.erb
<h1>New usersubnum</h1>

<%= render 'form' %>

<%= link_to 'Back', usersubnums_path %>

app/views/usersubnums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subnum:</strong>
  <%= @usersubnum.subnum %>
</p>

<p>
  <strong>Status:</strong>
  <%= @usersubnum.status %>
</p>

<p>
  <strong>Createdate:</strong>
  <%= @usersubnum.createdate %>
</p>

<%= link_to 'Edit', edit_usersubnum_path(@usersubnum) %> |
<%= link_to 'Back', usersubnums_path %>