config/routes.rb
Algamswebsvc::Application.routes.draw do
  resources :cell_towers

  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"

  resources :usersubnums

  resources :users, except: :new

  resources :locweb_thepics

  resources :custpayments

  resources :btc_gsm_sig_survs

  resources :custinvoices

  get '/signup' => 'users#new'
  get '/towers_gmap' => 'cell_towers#towers_gmap'
  get '/algam' => 'sessions#new'
  post '/signin' => 'sessions#new'
  get '/signout' => 'sessions#destroy', via: :delete
  resources :sessions, only: :create

  root :controller => 'main', :action => :index

  get '/admin' => 'sessions#new'

  get "*rest" => "main#not_found"

end

app/models/api_key.rb
class ApiKey < ActiveRecord::Base

before_create :generate_access_token
  belongs_to :user
  
private
  def generate_access_token
    begin
      self.access_token = SecureRandom.hex
    end while self.class.exists?(access_token: access_token)
  end
end

app/models/btc_gsm_sig_surv.rb
class BtcGsmSigSurv < ActiveRecord::Base

after_initialize :default_values
#Below property is in case we do not hve the
#Lat and long which will take a geocode
#and generate the lat/long
#remember to add the css style sheet for the gmaps gem
#acts_as_gmappable :process_geocoding => false

private
 def default_values
  self.pic_timestamp = Time.now
  self.audit_create_date = Time.now
 end

 def gmaps4rails_address
  address
 end

 def btcgsmsigsurv_params
  params.require(:BtcGsmSigSurv).permit(:user_info, :latitude, :longitude, :sig_str, :pic_timestamp)
 end
end

app/models/cell_tower.rb
class CellTower < ActiveRecord::Base
  #Below property is in case we do not hve the
  #Lat and long which will take a geocode
  #and generate the lat/long
  #remember to add the css style sheet for the gmaps gem
  #acts_as_gmappable :process_geocoding => false

end

app/models/custinvoice.rb
class Custinvoice < ActiveRecord::Base
end

app/models/custpayment.rb
class Custpayment < ActiveRecord::Base
end

app/models/locweb_thepic.rb
class LocwebThepic < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
has_many :api_keys
has_secure_password
validates_presence_of :username, :email, :password, :on => :create
end

app/models/usersubnum.rb
class Usersubnum < ActiveRecord::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController
 protect_from_forgery
 @source_cont = "none"

 def index
  #defining custom home page
  @source_cont = "index"
  #render "main/custom_index.html.erb"

  #the previous routing stuff
  if Rails.env.production?
   {:host => "www.halalgami.tk"}
  else
  {}
  end
 end

 def not_found
  @source_cont = "notfound"
  render "layouts/application.html.erb"
 end

private
 def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
 end

 helper_method :current_user

 def authorize
  redirect_to signin_url, alert: "Not authorized" if current_user.nil?
 end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
   user = User.find_by_username(params[:username])
    if user && user.authenticate(params[:password])
      user.api_keys.create!
      session[:user_id] = user.id
      #redirect_to lists_url, notice: "Logged in!"
      case request.format
       when Mime::JSON
        format.json { render json: @session, status: :created }
       else
        redirect_to btc_gsm_sig_survs_path, notice: "Logged in!"
       end
    else
      flash.now.alert = "Invalid username or password"
      #render "new"
      redirect_to root_url
    end
  end

  def destroy
   session[:user_id] = nil
   redirect_to root_url, notice: "Logged out!"
   #redirect_to signout_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_filter :authorize, :correct_user, only: :show
  before_filter :correct_user, only: [:show, :edit, :update]
  #before_action :set_user, only: [:show, :edit, :update, :destroy]
  #stopping unauthorized access

  # GET /users
  # GET /users.json
  # commenting out the display of all
  #def index
  #  @users = User.all
  #end

  # GET /users/1
  # GET /users/1.json
  def show
   @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        #format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.html { redirect_to root_url, notice: 'User successfully created!' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  # restricting update too
  def update
    respond_to do |format|
      if @user.update(user_params)
        #format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.html { redirect_to current_user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  # commenting out the delete verb as well
  #def destroy
  #  @user.destroy
  #  respond_to do |format|
  #    format.html { redirect_to users_url }
  #    format.json { head :no_content }
  #  end
  #end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :email, :password_digest, :realname, :status, :userinfo, :password_confirmation)
      #params.require(:user).permit(:username, :password, :email, :realname, :userinfo, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/btc_gsm_sig_survs_helper.rb
module BtcGsmSigSurvsHelper
end

app/helpers/cell_towers_helper.rb
module CellTowersHelper
end

app/helpers/custinvoices_helper.rb
module CustinvoicesHelper
end

app/helpers/custpayments_helper.rb
module CustpaymentsHelper
end

app/helpers/locweb_thepics_helper.rb
module LocwebThepicsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/usersubnums_helper.rb
module UsersubnumsHelper
end

app/views/layouts/_application_custom.html.erb
<header id="header">
<div id="logo">Algam's Little Corner</div>
<nav id="naval">
	<ul>
	<li><a href="#posts" title="My Posts" >Posts</a></li>
	<li><a href="#portfolio" title="Product Portfolio">Portfolio</a></li>
	<li><a href="#about" title="About Algam">About Algam</a></li>
	</ul>
</nav>
</header>
      <div class="row-fluid">


          <%= bootstrap_flash %>
          <%= yield %>
          <%= yield :scripts %>

      </div><!--/row-->

      <footer id="copyright">
        <p>&copy; AlgamNet 2014</p>
      </footer>

app/views/layouts/_application_ws.html.erb
    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Algamswebsvc</a>
          <% if current_user.nil? %>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "GSM Signal Survey List", "/btc_gsm_sig_survs"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
          <% end %>
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "GSM Signal Survey List", "/btc_gsm_sig_survs"  %></li>
              <li><%= link_to "Signal Survey Map", "/path2"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
          <%= yield :scripts %>
        </div>
      </div><!--/row-->


      <footer>
        <p>&copy; AlgamNet 2014</p>
      </footer>

    </div> <!-- /container -->
  </body>
</html>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to "Algams WebService Portal", root_path, class: "brand" %>
      <div class="container nav-collapse">
        <ul class="nav">
          <li><%= link_to("Home", root_path) %></li>
          <li><%= link_to("About", "#") %></li>
          <li><%= link_to("Made by AlgamNet", "http://www.halalgami.tk") %></li>

        <% if current_user %>  
          <li id="fat-menu" class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user)%></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Sign out", signout_path %>
              </li>
            </ul>
          </li>
          <% else %>
            <li> <%= link_to "Sign in", signin_path %></li>
            <li> <%= link_to "Sign up", signup_path %> </li>
          <% end %>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/layouts/_not_found.html.erb
<header id="header">
<div id="logo">Algam's Little Corner</div>
<nav id="naval">
  <ul>
  <li><a href=<%= root_path %>#posts title="My Posts" >Posts</a></li>
  <li><a href=<%= root_path %>#portfolio title="Product Portfolio">Portfolio</a></li>
  <li><a href=<%= root_path %>#about title="About Algam">About Algam</a></li>
  </ul>
</nav>
</header>
      <div class="row-fluid">

        <div id="posts">
          <p><h1>Apologies ...</h1></p>
          <p><h2>The page you are looking for is not available</h2></p>
        </div>


      </div><!--/row-->

      <footer id="copyright">
        <p>&copy; AlgamNet 2014</p>
      </footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Algam's Little Corner" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <link rel="stylesheet" href="../stylesheets/the_css.css"/>
    <link href='http://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Great+Vibes' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Wellfleet' rel='stylesheet' type='text/css'>
    <script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
    <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
    <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
    <script type="text/javascript">

    $(document).ready(function() {
    $('a[href*=#]').each(function() {
    if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'')
    && location.hostname == this.hostname
    && this.hash.replace(/#/,'') ) {
    var $targetId = $(this.hash), $targetAnchor = $('[name=' + this.hash.slice(1) +']');
    var $target = $targetId.length ? $targetId : $targetAnchor.length ? $targetAnchor : false;
    if ($target) {
    var targetOffset = $target.offset().top;
    $(this).click(function() {
                $("#nav li a").removeClass("active");
                $(this).addClass('active');
    $('html, body').animate({scrollTop: targetOffset}, 1000);

    $(this).children().fadeOut( "slow", function() {
         $(this).addClass('active');
    });

    return false;
    });
    }
    }
    });

    //end of document ready
    });

    </script>
  </head>
  <body>

  <% if @source_cont=="index"%>
  <%= render 'layouts/application_custom' %>

  <% elsif @source_cont=="notfound"%>
  <%= render 'layouts/not_found' %>

  <% else%>
  <%= render 'layouts/header' %>
  <%= render 'layouts/application_ws' %>

  <% end%>
  </body>
</html>